CREATE USER MY_USER IDENTIFIED BY MY_USER QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE TO MY_USER;

CREATE TABLE MY_USER.CUSTOMERS
(
    "CUSTOMER_ID" NUMBER NOT NULL,
    "NAME" VARCHAR2(30 CHAR) NOT NULL
);